import Head from "next/head";
import {
  AiFillMail,
  AiFillLinkedin,
  AiFillGithub
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/dev-ed-wave.png";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import Link from 'next/link';



export default function Home() {
  const [darkMode, setDarkMode] = useState(true);
  const email = 'priyanshideshpande19@gmail.com';
  const linkedinURL = 'https://in.linkedin.com/in/priyanshi-deshpande-026718256';
  const githubURL = 'https://github.com/Priyanshi1908';

  const vercelProjectURL1 = 'https://metaverse-qxg5oxc36-priyanshi1908.vercel.app';
  const vercelProjectURL2 = 'https://defi-oeaf3dthl-priyanshi1908.vercel.app';
  
  

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="pt-5 mb- flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">Portfolio</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500  to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="https://drive.google.com/file/d/1EGNjN8Lm5xW1zZc5NL41Ghy2wMVJ-8ez/view?usp=sharing"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center ">
            <h2 className="text-5xl  text-teal-600 font-medium dark:text-teal-400 md:text-6xl pt-10 md:pt-5">
              Priyanshi Deshpande
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Developer and Designer.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Aspiring Junior developer providing services for programming and design content
              needs. Join me down below to see some of my projects.
            </p>
            
            <div className="text-5xl flex justify-center gap-16  text-gray-600 dark:text-gray-400">
           
              <div>
                <Link href="/blankpage">
                  <a>
                    <AiFillMail />
                  </a>
                </Link>
              </div>
            
            <div>
            <a href={linkedinURL} target="_blank" rel="noopener noreferrer">
            <AiFillLinkedin />
            </a>
            </div>

             <div>
             <a href={githubURL} target="_blank" rel="noopener noreferrer">

             <AiFillGithub />
             </a>
             </div>
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-3 md:h-80 md:w-80">
              <Image src={deved} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>


        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Services I offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
             
            As a React developer, I offer comprehensive services in building responsive and interactive web applications and optimizing performance for seamless user experiences.
            
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including
              <span className="text-teal-500"> Brand design,
              Frontend Consulting and Support, Responsive Website Development and Maintenance. </span> 
              
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  text-slate-200 bg-gradient-to-r from-cyan-900 to-cyan-400 dark:bg-gradient-to-r  dark:from-blue-950 dark:to-cyan-950 dark:text-white flex-1">
              <Image src={design} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Beautiful Designs
              </h3>
              <p className="py-2">
                Creating elegant designs suited for your needs following core
                design theory.
              </p>
              <h4 className="py-4 font-semibold text-indigo-900 dark:text-teal-600">Design Tools I Use</h4>
              <p className="text-gray-800 py-1 dark:text-slate-400">Tailwind CSS</p>
              <p className="text-gray-800 py-1 dark:text-slate-400">Canva</p>
              <p className="text-gray-800 py-1 dark:text-slate-400">Figma</p>
              <p className="text-gray-800 py-1 dark:text-slate-400">Framer</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10  text-slate-200 bg-gradient-to-r from-cyan-900 to-cyan-400 dark:bg-gradient-to-r  dark:from-blue-950 dark:to-cyan-950 dark:text-white flex-1">
              <Image src={code} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Code your dream project
              </h3>
              <p className="py-2">
              Do you have an idea for your next great website? Let's collaborate and make it a reality.
              </p>
              <h4 className="py-4 font-semibold text-indigo-900 dark:text-teal-600">Design Tools I Use</h4>
              <p className="text-gray-800 py-1 dark:text-slate-400">React Js</p>
              <p className="text-gray-800 py-1 dark:text-slate-400">Tailwind CSS</p>
              <p className="text-gray-800 py-1 dark:text-slate-400">Figma</p>
              <p className="text-gray-800 py-1 dark:text-slate-400">Illustrator</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10  text-slate-200 bg-gradient-to-r from-cyan-900 to-cyan-400 dark:bg-gradient-to-r  dark:from-blue-950 dark:to-cyan-950 dark:text-white flex-1">
              <Image src={consulting} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">Consulting</h3>
              <p className="py-2">
                Are you interested in feedback for your current project? I can
                give you tips and tricks to level it up.
              </p>
              <h4 className="py-4 font-semibold text-indigo-900 dark:text-teal-600">Design Tools I Use</h4>
              <p className="text-gray-800 py-1 dark:text-slate-400">React Js</p>
              <p className="text-gray-800 py-1 dark:text-slate-400">Tailwind CSS</p>
              <p className="text-gray-800 py-1 dark:text-slate-400">Figma</p>
              <p className="text-gray-800 py-1 dark:text-slate-400">Photoshop</p>
            </div>
          </div>
        </section>

        
        <section className="py-10">
          <div>
            <h3 className="text-4xl py-1 text-teal-600 ">Projects</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I am a designer and developer with an interest in Web Development and UI/UX design. 
              I'm an enthusiastic React developer with a strong foundation
              in front-end development. Eager to contribute and learn in a real-world startup environment, I bring a passion 
               for creating intuitive user interfaces with React.js.
               With a collaborative mindset and a drive to excel, I am ready to take on challenges, 
               contribute innovative ideas, and be an asset to your team.
            </p>
            
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className=" flex-1 ">
            <a href={vercelProjectURL1} target="_blank" rel="noopener noreferrer">

              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web1}
              />
              </a>
            </div>

            <div className=" flex-1 cursor-pointer">
            <a href={vercelProjectURL2} target="_blank" rel="noopener noreferrer">

              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web2}
              />
              </a>
            </div>
            



            {/* <div className=" flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web3}
              />
            </div> */}
            {/* <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web4}
              />
            </div> */}
            {/* <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web5}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web6}
              />
            </div> */}
          </div>
        </section>
      </main>
    </div>
  );
}
